import { afterEach, describe, expect, it } from 'vitest';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';

const repoRoot = resolve(import.meta.dirname, '../../..');
const entry = join(repoRoot, 'src/index.ts');

function runCli(cwd: string, args: string[]) {
  return spawnSync('bun', [entry, ...args], {
    cwd,
    encoding: 'utf-8',
    env: { ...process.env, NO_COLOR: '1', SPECIALISTS_INIT_FORCE: '1' },
  });
}

function specialistJson(name: string) {
  return JSON.stringify({
    specialist: {
      metadata: {
        name,
        version: '1.0.0',
        description: `${name} description`,
        category: 'integration',
      },
      execution: {
        model: 'anthropic/claude-sonnet-4-6',
        permission_required: 'LOW',
        interactive: false,
      },
      prompt: {
        task_template: 'Do $prompt',
      },
    },
  }, null, 2);
}

describe('integration: migration docs and operator guidance alignment', () => {
  let tempDir = '';

  afterEach(async () => {
    if (tempDir) {
      await rm(tempDir, { recursive: true, force: true });
      tempDir = '';
    }
  });

  it('documents ownership layers, precedence ladders, migration do-not-edit, and backlog-clean isolation', async () => {
    const ownershipDoc = await readFile(join(repoRoot, 'docs', 'surface-ownership.md'), 'utf-8');

    expect(ownershipDoc).toContain('## Four-layer model');
    expect(ownershipDoc).toContain('Upstream source (package, read-only at runtime)');
    expect(ownershipDoc).toContain('Managed mirror (repo, generated by init sync)');
    expect(ownershipDoc).toContain('Repo authoring / custom layer (repo-owned)');
    expect(ownershipDoc).toContain('Runtime / generated state (never hand-author)');
    expect(ownershipDoc).toContain('.specialists/jobs/');
    expect(ownershipDoc).toContain('.specialists/ready/');
    expect(ownershipDoc).toContain('.specialists/db/');

    expect(ownershipDoc).toContain('### Specialists');
    expect(ownershipDoc).toContain('### Mandatory rules');
    expect(ownershipDoc).toContain('### Nodes');
    expect(ownershipDoc).toContain('1. `.specialists/user/`');
    expect(ownershipDoc).toContain('2. `.specialists/default/`');
    expect(ownershipDoc).toContain('3. `config/specialists/` (package fallback)');
    expect(ownershipDoc).toContain('1. explicit path (`specialists node run ./path/to/file.node.json`)');
    expect(ownershipDoc).toContain('2. `config/nodes/`');
    expect(ownershipDoc).toContain('3. `.specialists/default/nodes/`');

    expect(ownershipDoc).toContain('### Same-name override');
    expect(ownershipDoc).toContain('### New-name fork');
    expect(ownershipDoc).toContain('do not hand-edit `.specialists/default/*`');
    expect(ownershipDoc).toContain('run `specialists init --sync-defaults` to reconcile mirror drift');

    expect(ownershipDoc).toContain('## Explicit non-goal: backlog-clean isolation');
    expect(ownershipDoc).toContain('backlog-clean command behavior');
    expect(ownershipDoc).toContain('backlog-clean data model');
    expect(ownershipDoc).toContain('backlog-clean runtime hooks/automation');
  });

  it('keeps bootstrap and CLI reference guidance aligned for init/edit/validate/doctor/node ownership semantics', async () => {
    const bootstrapDoc = await readFile(join(repoRoot, 'docs', 'bootstrap.md'), 'utf-8');
    const cliReferenceDoc = await readFile(join(repoRoot, 'docs', 'cli-reference.md'), 'utf-8');

    expect(bootstrapDoc).toContain('Do not hand-edit files under `.specialists/default/`.');
    expect(bootstrapDoc).toContain('For custom behavior use `.specialists/user/` (specialists) or `config/nodes/` (nodes).');
    expect(bootstrapDoc).toContain('specialists init --sync-defaults');

    expect(cliReferenceDoc).toContain('validate` resolves specialist by runtime precedence (`user` -> `default-mirror` -> `package-fallback`)');
    expect(cliReferenceDoc).toContain('`list`: List discovered node configs from `config/nodes` then `.specialists/default/nodes` (repo wins on collision).');
    expect(cliReferenceDoc).toContain('`.specialists/default/` is managed mirror; do not hand-edit');
    expect(cliReferenceDoc).toContain('`.specialists/user/` is repo customization/fork layer');
    expect(cliReferenceDoc).toContain('`--sync-defaults` | Refresh managed mirror into `.specialists/default/` for specialists, mandatory-rules, and nodes. Human-only.');
    expect(cliReferenceDoc).toContain('Managed mirrors');
  });

  it('matches docs with real CLI behavior for node help and validate ownership precedence', async () => {
    tempDir = await mkdtemp(join(tmpdir(), 'specialists-docs-int-'));
    await mkdir(join(tempDir, '.specialists', 'default'), { recursive: true });
    await mkdir(join(tempDir, '.specialists', 'user'), { recursive: true });

    await writeFile(join(tempDir, '.specialists', 'default', 'alpha.specialist.json'), specialistJson('alpha'), 'utf-8');
    await writeFile(join(tempDir, '.specialists', 'user', 'alpha.specialist.json'), specialistJson('alpha'), 'utf-8');

    const nodeHelp = runCli(tempDir, ['node', '--help']);
    expect(nodeHelp.status).toBe(0);
    expect(nodeHelp.stdout).toContain('List node configs; source order: repo config/nodes -> .specialists/default/nodes');
    expect(nodeHelp.stdout).toContain('Node configs: explicit path wins; named lookup prefers repo config/nodes, then .specialists/default/nodes.');

    const doctorResult = runCli(tempDir, ['doctor']);
    expect(doctorResult.stdout).toContain('Managed mirrors');

    const validateResult = runCli(tempDir, ['validate', 'alpha', '--json']);
    expect(validateResult.status).toBe(0);
    const payload = JSON.parse(validateResult.stdout);
    expect(payload.source).toBe('user/user');
    expect(payload.file).toContain('.specialists/user/alpha.specialist.json');
  });
});
